services:
  node1:
    build: .
    environment:
      NODE_ID: node1
      PORT: 5000
    ports:
      - "5001:5000"
    networks:
      - cluster

  node2:
    build: .
    environment:
      NODE_ID: node2
      PORT: 5000
    ports:
      - "5002:5000"
    networks:
      - cluster

  node3:
    build: .
    environment:
      NODE_ID: node3
      PORT: 5000
    ports:
      - "5003:5000"
    networks:
      - cluster

  node4:
    build: .
    environment:
      NODE_ID: node4
      PORT: 5000
    ports:
      - "5004:5000"
    networks:
      - cluster

  node5:
    build: .
    environment:
      NODE_ID: node5
      PORT: 5000
    ports:
      - "5005:5000"
    networks:
      - cluster

networks:
  cluster:
